DevCycleHQ/cli

package.json
src/api/variables.ts
src/commands/diff/index.ts
test/commands/diff.test.ts
test/utils/diff/samples/e2e

This is intended to handle the case where multiple parsers match on the same line

Handle duplicates matches on the same line

---

src/commands/diff/index.ts
test/commands/diff.test.ts

It looks like this:
🟢  0 Variables Added
🔴  0 Variables Removed

output svg banner for markdown

---

src/utils/parsers/common.ts
src/utils/parsers/types.ts

- new function `extractUsageInformation` that takes the `File` object and the `MatchWithRange` to find the variable usage from the start and end indices.

feat: multi line method calls usage

---

src/commands/usages/index.ts
src/utils/parsers/common.ts
test/commands/usages.test.ts
test/utils/parsers/android.test.ts
test/utils/parsers/csharp.test.ts
test/utils/parsers/golang.test.ts
test/utils/parsers/ios.test.ts
test/utils/parsers/java.test.ts
test/utils/parsers/javascript.test.ts
test/utils/parsers/nodejs.test.ts
test/utils/parsers/php.test.ts
test/utils/parsers/python.test.ts
test/utils/parsers/react.test.ts
test/utils/parsers/ruby.test.ts
test/utils/usages/samples/nodejs.js

Added a test and found some edge cases

Add basic test for `dvc usages`

---

src/utils/parsers/common.ts

- added check for start of line if it starts with a comment
- still needs to take in account comments added at the end of a line

feat: handle single line comments

---

src/utils/parsers/common.ts
src/utils/parsers/types.ts

- added language to results in results by language map

feat: Include file language in match result

---

.github/workflows/tests.yml
src/commands/usages/index.ts
src/commands/usages/types.d.ts
src/utils/parsers/common.ts
src/utils/parsers/types.ts
src/utils/usages/parse.ts
test/commands/usages.test.ts

- change output of json format to be compatible with API input

feat: update json output structure

---

src/utils/diff/parse.ts
src/utils/parsers/BaseParser.ts
src/utils/parsers/android/index.ts
src/utils/parsers/csharp/index.ts
src/utils/parsers/custom.ts
src/utils/parsers/golang/index.ts
src/utils/parsers/index.ts
src/utils/parsers/ios/index.ts
src/utils/parsers/java/index.ts
src/utils/parsers/javascript/index.ts
src/utils/parsers/nodejs/index.ts
src/utils/parsers/php/index.ts
src/utils/parsers/python/index.ts
src/utils/parsers/react/index.ts
src/utils/parsers/ruby/index.ts
src/utils/usages/parse.ts
test/commands/usages.test.ts
test/utils/usages/samples/nodejs.js

Also moved PARSERS to a common location and updated "common.ts" to "BaseParser.ts" for clarity

Handle trailing comma after last param

---

src/api/ssoAuth.ts

Port 5000 is used by upnp, so the default needs to be changed to an
unassigned port. There is support for overriding the port, but the
oauth flow requires us to specify callback urls against specific port
numbers, so it's necessary to have a fixed list of supported ports.

[DVC-2660] Change the default port

---

package.json

This version is needed by the new SSO login code.

[DVC-2666] Update minimum node version to 14.18.0

---

src/auth/getToken.ts
src/commands/base.ts
src/commands/login/sso.ts
src/commands/logout/index.ts
src/commands/org/index.ts
src/ui/togglebot.ts

I also added logout so that I could easily test logging in and out again

Dvc 2797 config files shouldn't be stored in current directory by default

---

src/commands/authCommand.ts
src/commands/projects/select.ts

If you had a saved project, it would read that project from the configuration instead of asking you to choose one.

fix projects select command

---

src/utils/refactor/RefactorEngine.ts
src/utils/refactor/utils.ts
test/commands/cleanup.test.ts
test/commands/fixtures/cleanup/javascript/test.js

When cleaning up a variable, remove any variable.onUpdate blocks

Add handling for variable.onUpdate

---

src/utils/parsers/golang/index.ts
test/utils/diff/parsers/golang.test.ts
test/utils/diff/samples/golang
test/utils/usages/samples/golang.go

Update `golang` parser to capture new method signature changes

chore: update cli to capture go changes to sdk

---

src/commands/authCommand.ts
src/commands/login/sso.ts
src/commands/org/index.ts
src/commands/projects/select.ts
src/commands/repo/init.ts
src/ui/promptForProject.ts

- select organization when the flag is passed into the `projects select` command

[fix] select org from flag before prompting projects select

---

docs/variations.md
oclif.manifest.json
src/commands/variations/get.ts

https://github.com/DevCycleHQ/cli/assets/25067948/7e8e8d02-1770-4fd7-aa5c-9e182bd8fce6
(`get.ts` is exactly the same as `list.ts` but it directly returns the whole variables list instead of mapping it to only return the keys)

Add variations get command

---

docs/features.md
oclif.manifest.json
src/api/features.ts
src/commands/features/delete.ts

- add `features delete` command
- required feature arg

[feat] add features delete

---

src/commands/environments/update.ts

Just removing the feature prompt from the environments update command

remove the prompt for _feature from environments update

---

src/api/apiClient.ts

[fix] add dvc-referrer and dvc-metadata properly to cli

---

src/commands/environments/get.ts
src/commands/environments/update.ts
src/commands/keys/get.ts
src/commands/targeting/disable.ts
src/commands/targeting/enable.ts
src/ui/prompts/environmentPrompts.ts
src/ui/prompts/index.ts

fix: Correct environment name

---

package.json
src/commands/variations/list.test.ts
test-utils/dvcTest.ts
test-utils/index.ts
tsconfig.json

Add variation list tests colocated with command file
Note: skip headless test until fix is merged

chore: Add variation list tests

---

src/api/apiClient.ts
src/api/organizations.ts
src/ui/promptForProject.ts

Use enquirer autocomplete for project select

---

src/commands/createCommand.ts
src/ui/prompts/commonPrompts.ts
src/ui/prompts/types.ts
src/ui/prompts/variablePrompts.ts

- Added transformer property to prompt to be able to format the input for hint texts

feat: added hint text transformer function to show hints when field is empty

---

README.md
docs/help.md
docs/variations.md
oclif.manifest.json
src/api/variations.ts
src/commands/base.ts
src/commands/updateCommand.ts
src/commands/variations/__snapshots__/update.test.ts.snap
src/commands/variations/create.ts
src/commands/variations/update.test.ts
src/commands/variations/update.ts
src/ui/prompts/commonPrompts.ts
src/ui/prompts/types.ts
src/ui/prompts/variablePrompts.ts
src/ui/prompts/variationPrompts.ts
src/utils/variations/index.ts

Known Issues:
- not using Zod for populateParameters
- missing hint text and proper defaulting on the variable editing

Dvc 7635 command dvc variations update

---

docs/targeting.md
oclif.manifest.json
src/api/schemas.ts
src/api/targeting.ts
src/api/zodClient.ts
src/commands/targeting/__snapshots__/update.test.ts.snap
src/commands/targeting/update.test.ts
src/commands/targeting/update.ts
src/commands/updateCommand.ts
src/ui/prompts/listPrompts/filterListPrompt.ts
src/ui/prompts/listPrompts/targetingListPrompt.ts
src/ui/prompts/listPrompts/variablesListPrompt.ts
src/ui/prompts/targetingPrompts.ts
src/ui/prompts/types.ts
src/ui/prompts/variationPrompts.ts
src/utils/prompts.ts

* Add `targeting update command`
https://github.com/DevCycleHQ/cli/assets/33500361/6840d103-df6c-48c8-a693-959ab7c41fa2

feat: add targeting update command

---

src/ui/prompts/variablePrompts.ts

chore: add hint text for variable value type

chore: add hint text for variable value type

---

src/ui/prompts/variationPrompts.ts

- add variable type as hint text to variations update command

chore: add variable type as hint text to variations update

---

src/ui/prompts/listPrompts/filterListPrompt.ts
src/ui/prompts/listPrompts/listOptionsPrompt.ts
src/ui/prompts/listPrompts/targetingListPrompt.ts
src/ui/prompts/listPrompts/variablesListPrompt.ts
src/ui/prompts/listPrompts/variationsListPrompt.ts

- move ContinuePrompt be the first one of the list

chore: move ContinuePrompt be the first one of the list

---

src/ui/targetingTree.ts

chore: add AND to targeting tree

---

src/ui/constants/colors.ts
src/ui/targetingTree.ts

chore: add colors to the tree

---

DEVELOPMENT.md
README.md

- Move development details to separate markdown file
- Update headers to work with docusaurus linking (top level `#` does not create links)

Update readme to use in documentation

---

README.md
docs/autocomplete.md
package.json
yarn.lock

* Add tab completion via the autocomplete plugin for oclif
https://github.com/DevCycleHQ/cli/assets/33500361/7e17820d-630c-47e0-b3e6-e892b0320ba3

feat: add tab completion

---

src/commands/environments/update.ts
src/commands/features/update.ts
src/commands/targeting/__snapshots__/update.test.ts.snap
src/commands/variables/update.ts
src/commands/variations/update.ts
src/ui/prompts/listPrompts/filterListPrompt.ts
src/ui/prompts/listPrompts/listOptionsPrompt.ts
src/ui/prompts/listPrompts/targetingListPrompt.ts
src/ui/writer.ts

chore: update prompt values color and heading

---

docs/usages.md
oclif.manifest.json
src/commands/usages/__snapshots__/usages.test.ts.snap
src/commands/usages/index.ts
src/commands/usages/usages.test.ts
test-utils/fixtures/usages/nodejs.js

- added flag to `usages` to only list variable usages that aren't a variable in your project already

feat: add flag to usages to only list variable usages that arent a variable in the api

---

src/api/ssoAuth.ts

- update the auth page 
- remove close button and the auto close page

chore: remove close button and auto close

---

oclif.manifest.json
package.json
yarn.lock

* changes in oclif.manifest.json are from not building after making updates to a command in a previous PR

chore: remove deprecated @types/axios package

---

src/auth/ApiAuth.ts

Add full error message to refresh token error and prompt user to login again

fix: Add more details to refresh token error

---

docs/variables.md
oclif.manifest.json
src/api/features.ts
src/api/variables.ts
src/commands/features/get.test.ts
src/commands/features/get.ts
src/commands/features/list.test.ts
src/commands/features/list.ts
src/commands/variables/get.ts
src/commands/variables/list.test.ts
src/commands/variables/list.ts

- Add `search` flag to variable and feature `list` and `get` commands
- Add `page` and `per-page` flags to feature `list` and `get` commands

feat: Add search params to variable and feature commands

---

src/commands/variables/create.test.ts
src/commands/variables/create.ts
src/ui/prompts/featurePrompts.ts
src/ui/prompts/variablePrompts.ts

- added prompt before prompting to attach to a feature to ask user if they want to attach variable to a feature

chore: remove variable feature prompt from create variable prompts, prompt manually in create command

---

docs/overrides.md
oclif.manifest.json
src/api/overrides.ts
src/api/zodClient.ts
src/commands/overrides/get.ts

- adds all flag to overrides GET command
- add table related flags to be used when getting all Project overrides
- adds ux.table output for all flags

DVC-8696 [feat]: add ability to get all Overrides for a user in a project

---

src/commands/overrides/list.ts
src/utils/environments/index.ts
src/utils/overrides/index.ts

- introduces default sorting for overrides list command

DVC-8827 [fix]: adds defaults sort by feature name then by environment type display order (dev, staging, prod)

---

src/auth/SSOAuth.ts

- When waiting for server to close, timeout after 2 mins
- When the server encounters an error exit the sso command

Add timeout to sso login

---

docs/projects.md
oclif.manifest.json
src/commands/base.ts
src/commands/keys/get.ts
src/commands/login/again.ts
src/commands/projects/current.ts
src/commands/projects/list.ts
src/commands/status/index.ts
src/types/configFile.ts

`projects current`
`status`
`projects list`
`keys get`
`login again`

feat: add command to display current project

---

docs/projects.md
oclif.manifest.json
src/api/projects.ts
src/commands/getCommand.ts
src/commands/projects/get.ts

- add `sortBy` and `sortOrder` flags to projects get command

feat: add sortBy and sortOrder flags to projects get command

---

docs/autocomplete.md
docs/help.md
package.json
yarn.lock

Remove `watch` lib which removes vulnerable `merge` dependency

chore: Remove watch lib

---

oclif.manifest.json
src/commands/usages/__snapshots__/usages.test.ts.snap
src/commands/usages/usages.test.ts
src/utils/getFilteredFiles.ts

* getFilteredFiles now tries to match for both escaped and unescaped characters
* add test

fix: magic characters in include and exclude globs

---

README.md
docs/help.md
oclif.manifest.json
src/commands/cleanup/index.ts

- update cleanup command to use new `FileFilters` class that uses options `includeFiles` and `excludeFiles` properly

fix: update cleanup command to use new FileFilters

---

README.md
oclif.manifest.json
src/api/members.ts
src/commands/generate/types.test.ts
src/flags/var-alias/index.ts

- fix the issue which displays Unknown User because of pagination issue

fix: add pagination for organization members api call

---

README.md
oclif.manifest.json
src/api/members.ts
src/commands/generate/types.test.ts

- tested with perPage as 5 to test locally and ensure the type generation works as expected

fix: pagination bug fix

---

yarn.lock

chore: update braces dep

---

README.md
docs/alias.md
docs/cleanup.md
docs/diff.md
docs/environments.md
docs/features.md
docs/generate.md
docs/identity.md
docs/keys.md
docs/login.md
docs/logout.md
docs/organizations.md
docs/overrides.md
docs/projects.md
docs/repo.md
docs/status.md
docs/targeting.md
docs/usages.md
docs/variables.md
docs/variations.md
package.json

This reverts commit 774d4c6102a29cc55b7faa4ab28039ff406a031d.

Revert "Release v5.15.0"

---

README.md
docs/alias.md
docs/cleanup.md
docs/diff.md
docs/environments.md
docs/features.md
docs/generate.md
docs/identity.md
docs/keys.md
docs/login.md
docs/logout.md
docs/organizations.md
docs/overrides.md
docs/projects.md
docs/repo.md
docs/status.md
docs/targeting.md
docs/usages.md
docs/variables.md
docs/variations.md
package.json

This reverts commit d8530b398b5468bbd67704a1ffdea6076569ff4c.

Revert "Release v5.14.15"

---

README.md
docs/generate.md
oclif.manifest.json
src/api/customProperties.ts
src/api/schemas.ts
src/api/zodClient.ts
src/commands/generate/__snapshots__/types.test.ts.snap
src/commands/generate/types.test.ts
src/commands/generate/types.ts

- add the ability to generate custom data typings from custom property definitions and schemas

feat: add custom data generator

---

oclif.manifest.json
package.json
yarn.lock

chore: update dependancies

---

yarn.lock

chore: update axios dep

---

mcp-worker/src/consentScreen.ts

- update mcp auth screen to match styles of the auth0 screens

Update mcp auth screen

---

src/mcp/types.ts

fix: update self target description

---

package.json
yarn.lock

feat: remove zod resolution, update to latest 3.x version
