src/commands/diff/index.ts
test/commands/diff.test.ts

Add an option to have fancy markdown formatting to increase readability. It looks like this:
✅  1 Variable Added
❌  0 Variables Removed
1. **optional-accessor**
Location: services/api/src/organizations/organizations.controller.ts:L177

add formatting option for markdown

---

README.md
src/commands/diff/index.ts
src/utils/diff/parse.ts
src/utils/diff/parsers/common.ts
src/utils/diff/parsers/types.ts
test/commands/diff.test.ts

Adds a flag that lets you print all the patterns used while evaluating your diff:
Pattern for nodejs parser: (?:dvcClient)\??\.variable\(\s*(?:\w*|{[^})]*}|new[^)]*\))\s*,\s*([^,)]*)\s*,\s*(?:[^),]*|{[^}]*})\)
Pattern for react parser: useVariable\(\s*([^,)]*)\s*,\s*(?:[^),]*|{[^}]*})\)
Pattern for javascript parser: (?:dvcClient)\??\.variable\(\s*([^,)]*)\s*,\s*(?:[^),]*|{[^}]*})\)
DevCycle Variable Changes:
✅  0 Variables Added
❌  0 Variables Removed

add show-regex option to diff command

---

README.md
src/utils/diff/parsers/common.ts
src/utils/diff/parsers/custom.ts
test/commands/diff.test.ts
test/commands/fixtures/customMatcherConfig.yml
test/utils/diff/parsers/nodejs.test.ts
test/utils/diff/parsers/react.test.ts
test/utils/diff/samples/custom-pattern

- Update readme to specify that custom match pattern must include the entire key parameter, including quotes if applicable
- Remove development section from readme
- Add isUnknown property to custom matches based on whether quotes are found

Identify variable aliases found with custom matcher

---

src/commands/usages/index.ts
src/utils/parsers/BaseParser.ts
src/utils/parsers/index.ts

Using the parser identity to determine the language does not work in the CustomParser case (returns 'custom' as the language). Instead, map the file extension to the language

Map file extensions to language

---

package.json

This is a temporary measure until node 17 compatibility issues are worked out.

[DVC-2701] Add node 17 incompatibility to package.json

---

README.md
docs/diff.md
docs/features.md
docs/login.md
docs/logout.md
docs/org.md
docs/projects.md
docs/usages.md
docs/variables.md
package.json
src/commands/base.ts
src/commands/diff/index.ts
src/commands/login/sso.ts
src/commands/org/index.ts
src/commands/projects/select.ts
src/commands/usages/index.ts
src/flags/client-name/index.ts
src/flags/match-pattern/index.ts
src/flags/var-alias/index.ts
src/types/configFile.ts
src/ui/output.ts
test/commands/diff.test.ts

User configuration should not be stored in the repo, so we need
separate configuration files to handle repo-configuration that the
diff and usages commands rely on from cli user configuration and
session data.

DVC-3490 Separate repo config from user config

---

docs/cleanup.md
docs/diff.md
docs/logout.md
docs/org.md
docs/status.md
docs/usages.md
src/commands/cleanup/index.ts
src/ui/prompts/variablePrompts.ts

If variable.key is not set, and variable list prompt fails, prompt user to enter a variable key rather than throwing an error

Cleanup: if api is unavailable prompt user for variable key

---

src/commands/usages/index.ts

Our default parsers will only include matches where the key is a string or the key matches an alias. For custom regex patterns we should include all matches.

Usages Command: Include all matches from custom regex in the results

---

src/commands/authCommand.ts

Currently when selecting a project within a repo only the repo config will be updated. This results in a 404 when running a command that does not require repo context (ie. `features list`), because the stored project does not belong to the authenticated org

[fix] When selecting a project, always update user config

---

src/commands/base.ts
src/commands/diff/index.ts
src/utils/parsers/dart/index.ts
src/utils/parsers/index.ts
test-utils/fixtures/diff/dart
test-utils/fixtures/usages/sample.dart
test/diff-parser/parsers/dart.test.ts

- Add support for parsing dart files with `dvc usages` and `dvc diff` commands
- When `no-api` flag is passed, don't call API even if project/keys are defined

[feat] Add support for parsing dart files

---

src/auth/config.ts
src/commands/authCommand.ts
src/commands/base.ts

- fix the `login again` command when not using `repo-level` configs by writing the `organization` choice to the `user.yml` file in the `.config/devcycle` directory.

fix login again command

---

README.md
docs/targeting.md
oclif.manifest.json
src/api/targeting.ts
src/commands/targeting/get.ts

- Adds new command of `dvc targeting get <feature-key> --env <env-key>`
- `--env <env-key>` can also be shorted to `-e <env-key>`
- `<feature-key>` is required, if not specified the user will be prompted to select one
- `<env-key>` is optional

DVC-7629 [feat]: add command to get targeting rules for a specific feature

---

README.md
docs/targeting.md
oclif.manifest.json
package.json
src/api/targeting.ts
src/commands/targeting/disable.ts
src/commands/targeting/enable.ts
src/commands/targeting/get.ts

- refactor `dvc targeting get <feature> <env>` to have `<env>` as a param instead of a `--env` flag
- add `dvc targeting enable <feature> <env>`
- add `dvc targeting disable <feature> <env>`

DVC-7630 [feat]: add enable / disable targeting functionality

---

src/api/variables.ts
test/commands/generate-types.test.ts

- dvc generate types will NOT include archived variables in the type definition

DVC-7709 [fix]: generate types command excludes archived variables

---

README.md
docs/environments.md
docs/variables.md
docs/variations.md
oclif.manifest.json
src/api/variables.ts
src/api/variations.ts
src/commands/cleanup/index.ts
src/commands/createCommand.ts
src/commands/environments/create.ts
src/commands/projects/create.ts
src/commands/variables/create.ts
src/commands/variations/create.ts
src/commands/variations/get.ts
src/commands/variations/list.ts
src/ui/prompts/variablePrompts.ts

TODO: add some tests! -- tested manually, will create ticket for tests
- add variations create command
- prompts for variables values (with proper types) if optional variables flag is not passed in
- ~~refactor cleanup command to use updated variable values prompt, which returns the correct types now~~
- keep the cleanup command variable values prompt to use `variableValueStringPrompt`, as the types are handled in `src/utils/refactor/RefactorEngine.ts`
JSON variable:

[feat] add variations create

---

src/commands/base.ts
src/commands/targeting/get.test.ts
src/commands/targeting/get.ts
src/commands/variations/list.test.ts

- Update `dvc targeting get` to include prompt for environment:
If a feature is specified, do not use any prompts. Otherwise prompt for feature and environment
- Add tests for `dvc targeting get` command
- Small fixes to auth error message and variation list test

DVC-7749 Update `targeting get` to prompt for environment

---

docs/environments.md
docs/variables.md
oclif.manifest.json
src/commands/base.ts
src/commands/createCommand.ts
src/commands/environments/create.ts
src/commands/environments/update.ts
src/commands/projects/create.ts
src/commands/updateCommand.ts
src/commands/variables/create.test.ts
src/commands/variables/create.ts
src/commands/variables/update.ts
src/commands/variations/create.ts
src/ui/prompts/environmentPrompts.ts
src/ui/prompts/index.ts
src/ui/prompts/types.ts
src/ui/prompts/variablePrompts.ts
src/utils/prompts.ts

* this also addresses[ DVC-7620](https://taplytics.atlassian.net/browse/DVC-7620)
* move `populateParameters` into `Base` class
* add `key` validation for headless mode on variable and environment update
* display variable key along with the name on variable choice prompt

fix: headless mode being ignored on variable and environment update

---

package.json
src/api/apiClient.ts
src/api/schemas.ts
src/commands/targeting/__snapshots__/get.test.ts.snap
src/commands/targeting/get.test.ts
src/commands/targeting/get.ts
src/ui/targetingTree.ts
test-utils/index.ts
test-utils/setCurrentTestFile.ts
yarn.lock

- Display targeting rules as tree when not running headless mode
- Update `targeting get` tests to use snapshots
TODO: in a follow up PR, add unit tests for targeting tree utils

feat: Print targeting rules using Tree when not running headless mode

---

src/api/apiClient.ts
src/api/schemas.ts
src/api/variables.ts
src/commands/base.ts
src/commands/features/create.test.ts
src/commands/features/create.ts
src/commands/variables/create.ts
src/commands/variables/update.ts
src/ui/prompts/featurePrompts.ts
src/ui/prompts/listPrompts/listOptionsPrompt.ts
src/ui/prompts/listPrompts/variablesListPrompt.ts
src/ui/prompts/variablePrompts.ts
src/utils/reportValidationErrors.ts

swapped out CreateVariableParams for CreateVariableDto and UpdateVariableDto from the zod schema
also updated the error messages so that it shows `___ is a required field` if the field is missing and can also handle min and max length, and mismatched enums. 
unfortunately zod doesn't give you access to the failing regex if it's a regex issue, so the best i could do is log `format of ___ is invalid`

Use zod schema for CreateVariableDto

---

src/commands/base.ts
src/commands/diff/diff.test.ts
src/commands/environments/create.ts
src/commands/environments/update.ts
src/commands/features/create.ts
src/commands/variables/create.ts
src/commands/variables/update.ts
src/commands/variations/update.ts
src/ui/prompts/listPrompts/listOptionsPrompt.ts

Override the `catch` function on the `Command` class in the base class.  This will make it so that we dont need to add as much custom error handling in the command methods for things like api errors and zod validation errors

add generic catch to base command class

---

docs/features.md
oclif.manifest.json
src/api/features.ts
src/api/schemas.ts
src/commands/base.ts
src/commands/features/__snapshots__/update.test.ts.snap
src/commands/features/create.test.ts
src/commands/features/create.ts
src/commands/features/update.test.ts
src/commands/features/update.ts
src/commands/updateCommand.ts
src/ui/prompts/commonPrompts.ts
src/ui/prompts/featurePrompts.ts
src/ui/prompts/listPrompts/variablesListPrompt.ts
src/ui/prompts/types.ts

In order to be able to include the variables and sdkVisibility prompts in the update choices list and only prompt for them if they're selected, i had to make these changes:
- changed `sdkVisibilityPrompt` to `getSdkVisibilityPrompt` which returns a prompt we can include in the prompt lists instead of wrapping around the prompt function directly
- added `transformResponse` function to Prompt type to handle transforming the response from the prompt (because sdkVisibility has to be transformed from an array to an object)
- added `listOptionsPrompt` function to Prompt type to bypass calling inquirer.prompt directly and instead call a custom prompt wrapper (to trigger the VariationListOptions flow)
- created `handleCustomPrompts` function that decides whether to call `inquirer.prompt` or …

Add features update command

---

docs/features.md
oclif.manifest.json
src/api/schemas.ts
src/commands/features/create.test.ts
src/commands/features/create.ts
src/commands/features/update.ts
src/commands/variations/create.ts
src/commands/variations/update.ts
src/ui/prompts/commonPrompts.ts
src/ui/prompts/listPrompts/listOptionsPrompt.ts
src/ui/prompts/listPrompts/variationsListPrompt.ts
src/ui/prompts/types.ts
src/ui/prompts/variablePrompts.ts
src/ui/prompts/variationPrompts.ts

- added the add/edit functions in VariationsListPrompt
- renamed `getVariationVariableValuePrompts` to `promptForVariationVariableValues` and created a new variationPrompt `getVariationVariablesPrompts` that just returns the prompts without calling inquirer.prompt (so we can use it in the prompts lists)
- added the option to set `previousReponseFields` on listOptions prompt types, which lets us pass previous responses along to the list fields. This way if you add or edit variables, the updated variables list is available in the variations prompt 
features create:
features update:

Prompt for variations in features create / update:

---

src/commands/targeting/update.test.ts
src/ui/prompts/listPrompts/filterListPrompt.ts
src/ui/prompts/listPrompts/listOptionsPrompt.ts
src/ui/prompts/listPrompts/targetingListPrompt.ts
src/ui/prompts/listPrompts/variablesListPrompt.ts
src/ui/prompts/listPrompts/variationsListPrompt.ts

* add `id` field to the ListOption type so that subclasses that don't have a unique identifier can easily be identified
* add reordering prompt to targeting list
* fix reorder prompt

feat: add id field to ListOption

---

docs/features.md
oclif.manifest.json
src/api/environments.ts
src/commands/base.ts
src/commands/environments/create.ts
src/commands/features/create.test.ts
src/commands/features/create.ts
src/commands/features/update.ts
src/commands/projects/create.ts
src/commands/variations/create.ts
src/commands/variations/update.ts
src/ui/prompts/commonPrompts.ts
src/ui/prompts/variablePrompts.ts
src/ui/prompts/variationPrompts.ts
src/utils/features/quickCreateFeatureUtils.ts

Made the default behaviour of `features create` to only prompt name, key, description and then use presets for `variables`, `variations`, and `targeting` to make it more seamlined.

feat: made features create command a quick create, added interactive mode

---

src/commands/features/create.test.ts
src/commands/features/create.ts

- add suggested command to feature creation

chore: add suggested command to feature creation

---

.github/workflows/tests.yml
package.json
src/commands/targeting/__snapshots__/update.test.ts.snap
src/commands/targeting/update.test.ts
src/commands/targeting/update.ts
src/ui/prompts/listPrompts/filterListPrompt.ts
src/ui/prompts/listPrompts/targetingListPrompt.ts
src/ui/targetingTree.ts

- Update `targeting update` output to display tree when not in headless mode
- Update targeting list prompts to display current targeting and filter values as tree

feat: Display targeting as tree in update command

---

src/commands/base.ts
src/commands/environments/create.ts
src/commands/environments/update.ts
src/commands/features/create.ts
src/commands/features/update.ts
src/ui/prompts/commonPrompts.ts
src/ui/prompts/listPrompts/listOptionsPrompt.ts
src/ui/prompts/listPrompts/targetingListPrompt.ts
src/ui/prompts/listPrompts/variablesListPrompt.ts
src/ui/prompts/listPrompts/variationsListPrompt.ts
src/ui/prompts/targetingPrompts.ts
src/utils/prompts.ts
src/utils/reportValidationErrors.ts
src/utils/validators.ts

* Add validation for required values, kebob case, and max length
* Fix bug with listPromptOption when discarding changes
* Fix bug where `variation`/`variables` was being sent as an empty array after discarding changes for variation/variables changes on features update

chore: add validation to prompts

---

src/api/schemas.ts
src/ui/prompts/listPrompts/filterListPrompt.ts
src/ui/prompts/listPrompts/targetingListPrompt.ts
src/ui/targetingTree.ts

Currently the tree would always use "AND". Updated to display the prefix based on the operator

fix: Handle displaying OR operator in targeting tree

---

src/api/environments.ts
src/commands/targeting/disable.ts
src/commands/targeting/enable.ts
src/ui/prompts/environmentPrompts.ts
src/utils/targeting/index.ts

- Refactor enable / disable targeting commands to use common method
- output response of enable / disable targeting as a tree

chore: output targeting enable disable as a tree

---

src/commands/features/delete.ts
src/commands/features/update.test.ts
src/commands/features/update.ts
src/commands/targeting/disable.ts
src/commands/targeting/enable.ts
src/commands/targeting/get.test.ts
src/commands/targeting/get.ts
src/commands/targeting/update.ts
src/commands/variations/create.test.ts
src/commands/variations/create.ts
src/commands/variations/get.ts
src/commands/variations/list.test.ts
src/commands/variations/list.ts
src/commands/variations/update.ts
src/ui/prompts/featurePrompts.ts
src/utils/targeting/index.ts

- Change FeaturePrompt to return the full feature object rather than just the key
- VariableFeaturePrompt still just returns the key, uses a transformer on the feature prompt answer to do so
- Update everywhere that uses FeaturePrompt to support the new output
- Remove a bunch of redundant API calls to fetch the feature
- Fix a bug with variations create where it would send the featureKey as a query param to variables GET
- Update all affected unit tests to mock out the correct api calls

Dvc 8076 refactor feature prompt

---

docs/targeting.md
docs/variations.md
oclif.manifest.json
src/commands/environments/update.ts
src/commands/features/update.ts
src/commands/targeting/update.test.ts
src/commands/targeting/update.ts
src/commands/updateCommand.ts
src/commands/updateCommandWithCommonProperties.ts
src/commands/variables/update.ts
src/commands/variations/update.ts
src/ui/prompts/listPrompts/filterListPrompt.ts
src/ui/prompts/listPrompts/listOptionsPrompt.ts
src/ui/prompts/listPrompts/targetingListPrompt.ts
src/ui/prompts/listPrompts/variablesListPrompt.ts
src/ui/prompts/targetingPrompts.ts

* Update `targeting update` test
* Change `targeting update` command to use `populateParametersWithZod`
* Can now also update the env status from the `targeting update` command

chore: make targeting update command behave the same as other update commands

---

src/api/audiences.ts
src/api/schemas.ts
src/commands/targeting/disable.ts
src/commands/targeting/enable.ts
src/commands/targeting/get.test.ts
src/commands/targeting/get.ts
src/commands/targeting/update.test.ts
src/commands/targeting/update.ts
src/ui/prompts/listPrompts/filterListPrompt.ts
src/ui/prompts/listPrompts/listOptionsPrompt.ts
src/ui/prompts/listPrompts/targetingListPrompt.ts
src/ui/targetingTree.ts
src/utils/audiences/index.ts
src/utils/audiences/utils.test.ts

- handle audience match filter when rendering targeting list
- added audiences to constructor of list option classes to prevent fetching in multiple places

chore: handle outputting in targeting tree audience match filters

---

src/ui/prompts/listPrompts/filterListPrompt.ts
src/ui/prompts/targetingPrompts.ts

- Added support in filter list options prompt class to select `audienceMatch` filter values based on existing audiences

feat: support setting audienceMatch as a filter from list of existing audiences

---

src/commands/authCommand.ts
src/commands/base.ts
src/commands/environments/get.ts
src/commands/environments/list.ts
src/commands/environments/update.ts
src/commands/features/create.ts
src/commands/features/delete.ts
src/commands/features/get.ts
src/commands/features/list.ts
src/commands/features/update.ts
src/commands/generate/types.ts
src/commands/keys/get.ts
src/commands/login/sso.ts
src/commands/targeting/disable.ts
src/commands/targeting/enable.ts
src/commands/targeting/get.ts
src/commands/targeting/update.ts
src/commands/variables/create.ts
src/commands/variables/get.ts
src/commands/variables/list.ts
src/commands/variables/update.ts
src/commands/variations/create.ts
src/commands/variations/get.ts
src/commands/variations/list.ts
src/commands/variations/update.ts
yarn.lock

- Update headless `login sso` command to require an org flag
- Change the `login sso` command to never save the personal token to auth.yml (in order to prevent projects from a personal org being fetched and used)
- Update the `requireProject` function to take headless, project params. The function will now error if its headless mode and theres no project flag provided (unless there is a project key saved in the config file, meaning the user specified a project when logging in via sso)
- Update every command to call `requireProject` with the new params

change headless sso to work properly

---

README.md
docs/generate.md
oclif.manifest.json
src/ui/prompts/environmentPrompts.ts

- order environment list when prompted to be in order of `development`, `staging`, `production` types.

chore: order env list by type in development, staging, production order

---

oclif.manifest.json
package.json
src/auth/ApiAuth.ts
src/auth/SSOAuth.ts
src/auth/TokenCache.ts
src/auth/config.ts
src/auth/utils/getTokenExpiry.test.ts
src/auth/utils/getTokenExpiry.ts
src/auth/utils/getTokenPayload.test.ts
src/auth/utils/getTokenPayload.ts
src/auth/utils/index.ts
src/auth/utils/shouldRefreshToken.test.ts
src/auth/utils/shouldRefreshToken.ts
src/commands/authCommand.ts
src/commands/base.ts
src/commands/login/sso.ts
src/commands/repo/init.ts

- When fetching a new token with sso auth retrieve a refresh token as well
- When a token is within 1 hour of expiry and we have a refresh token available, fetch a new token
This allows users to login through the browser once, and then as long as they interact with the CLI within the refresh token expiry (15 days) the access token will be refreshed

feat: Use refresh token to fetch new token for sso auth

---

docs/org.md
docs/organizations.md
oclif.manifest.json
src/commands/organizations/select.ts

Rename `dvc org` to `dvc organizations select` to be consistent with naming pattern of other commands

refactor!: Rename 'dvc org' to 'dvc organizations select'

---

README.md

Update `docs/org.md` to `docs/organizations.md`

fix: Update outdated doc links

---

oclif.manifest.json
src/auth/ApiAuth.ts
src/auth/config.ts
src/auth/utils/getOrgIdFromToken.test.ts
src/auth/utils/getOrgIdFromToken.ts
src/auth/utils/getTokenPayload.ts
src/auth/utils/index.ts
src/commands/alias/add.ts
src/commands/base.ts
src/commands/cleanup/index.ts
src/commands/diff/index.ts
src/commands/usages/index.ts

When running any command within the context of a repo, if an org and project exist in the repo config use those.
- Update auth file to store tokens by org ID, so that user can switch between repos seamlessly
This is required to unblock the [multi-folder case for the vs code extension](https://taplytics.atlassian.net/browse/DVC-8462)

feat: Use org and project from repo config if it exists

---

src/auth/config.ts

Check if repo config exists before reading file. This change was accidentally missed in https://github.com/DevCycleHQ/cli/pull/250

fix: Check if repo config exists before reading file

---

src/commands/authCommand.ts
src/commands/organizations/select.ts

Selecting an org requires user auth (rather than client credential), update the command class to require this and use the correct token

fix: Update org select command to require user auth

---

src/api/zodClient.ts
src/commands/features/__snapshots__/update.test.ts.snap
src/commands/features/update.test.ts
src/commands/features/update.ts
src/ui/prompts/listPrompts/variablesListPrompt.ts
src/ui/prompts/variablePrompts.ts

- fix the zod schema so that it knows CreateVariableDTO.defaultValue is optional 
- add a prompt for variation values when adding or updating a variable on an existing feature
note: this is a little bit sketchy because when updating the variables list, we need to essentially update the feature variations list as a semi-related side effect. Because the functions on VariableListOptions have to return a valid list option, i couldn't figure out a cleaner way to update the feature variations than to store them on the VariableListOptions class and access them in the feature update command separately. if there's a better way let me know!!
New prompts when editing a variable within a feature update:
this prompt won't show up when updating a single variable outside of a feature, or if you select …

Prompt for variation values when updating feature variables

---

src/commands/variables/update.ts

Updating the _feature field on a variable isnt allowed from the patch endpoint, so remove it from the variables update command.

remove ability to change feature field in variables update command

---

.github/actions/release/action.yml
.gitignore
docs/variables.md
package.json

- Use oclif command to pack tarballs (including node binary)
- Update release action to build and upload packaged artifacts (these will be used by the vscode extension)

chore: Add build artifacts to release

---

src/commands/base.ts
src/commands/diff/diff.test.ts
src/commands/features/create.test.ts
src/commands/features/update.test.ts
src/commands/targeting/get.test.ts
src/commands/targeting/update.test.ts
src/commands/variables/create.test.ts
src/commands/variations/create.test.ts
src/commands/variations/list.test.ts
src/ui/writer.ts

Errors thrown by the CLI just being logged with a 0 exit code, so users of the CLI cannot properly handle errors.
Re-throw error after custom handling to be caught by the default oclif error handler as per their recommendation [in the docs](https://oclif.io/docs/error_handling/#error-handling-in-the-catch-method)

fix: Pass all errors to oclif error handler after custom handling

---

src/commands/base.ts

Don't re-log error from oclif error handler

fix: Don't log error from oclif error handler

---

src/auth/ApiAuth.ts

Currently an error will be thrown if token refresh fails, even if the command does not require auth. If token refresh fails, log the error message but return an empty string as the token — the default "auth required" message will be displayed if necessary

fix: Return empty string when token refresh fails

---

docs/variables.md
oclif.manifest.json
src/api/variables.ts
src/commands/variables/get.test.ts
src/commands/variables/get.ts
src/commands/variables/list.test.ts
src/commands/variables/list.ts
src/commands/variations/create.ts
src/ui/prompts/variablePrompts.ts
src/ui/prompts/variationPrompts.ts

Add `page` and `per-page` flags to variables `list` and `get` commands. This will support fetching all variables from the vscode extension

feat: Add pagination flags to variable list and get commands

---

src/auth/ApiAuth.ts
src/commands/base.ts

Use Writer to log from ApiAuth to only show log when not running in headless mode. Currently the log is printed in headless mode which breaks the json parsing of the output

fix: Use writer to log from ApiAuth

---

README.md
docs/identity.md
oclif.manifest.json
package.json
src/commands/identity/get.ts
src/ui/writer.ts

- added `dvc identity get` command
- can take project key as well, otherwise gets identity for current project
- chantal's project has a dvcUserId set, chantal 2.0 does not

feat: add dvc identity get command

---

README.md
docs/overrides.md
oclif.manifest.json
package.json
src/api/overrides.ts
src/api/zodClient.ts
src/commands/identity/update.ts
src/commands/overrides/clear.ts

- add command for `dvc override clear --all`
- add endpoint for `DELETE` Project Overrides

DVC-8635 [feat]: add CLI command to clear all overrides for a project

---

docs/overrides.md
oclif.manifest.json
src/api/overrides.ts
src/api/zodClient.ts
src/commands/overrides/clear.ts

- added command `dvc overrides clear --feature <feature> --environment <environment>`
- works in headless mode
- `--all` flag takes precedence if specified along with `--feature` and `--environment`
non-headless:
headless:

feat: add dvc overrides clear for feature and environment

---

src/commands/diff/__snapshots__/diff.test.ts.snap
src/commands/diff/diff.test.ts
src/commands/diff/index.ts

Update `dvc diff` command to output "No DevCycle Variables Changed" when no changes are found in diff. This will be used by the github actions to determine if a comment should be added to a PR

feat: Update output message when no variables changed in diff

---

README.md
docs/overrides.md
oclif.manifest.json
src/api/overrides.ts
src/api/schemas.ts
src/api/zodClient.ts
src/commands/overrides/update.ts

DVC-8633: feat: add overrides update

---

src/commands/overrides/list.ts
src/commands/overrides/update.ts

- updated the `overrides update` command to print the results in a table

chore: overrides update command to print results in table

---

.github/workflows/cli-release.yml

- Added step to trigger `homebrew-cli`  workflow after publishing to npm

chore: add repository dispatch step when publishing cli for homebrew tap

---

src/api/overrides.ts
src/api/zodClient.ts
src/commands/overrides/clear.ts
src/commands/overrides/get.ts
src/ui/prompts/environmentPrompts.ts
src/ui/prompts/featurePrompts.ts
src/ui/prompts/overridePrompts.ts
src/ui/prompts/types.ts
src/utils/variations/index.ts

- tested locally by changing the number of overrides through dashboard

DVC-8772 chore: filter prompts for overrides

---

src/commands/variations/update.test.ts
src/commands/variations/update.ts

Previously if you update variation values and only select some of the variables, the other variable values would be deleted.

Only update selected variation values instead of overriding all

---

docs/login.md
docs/organizations.md
docs/projects.md
docs/repo.md
src/commands/authCommand.ts
src/commands/repo/init.ts

Currently when calling `repo init` it will always open two browser windows. Avoid running the full sso auth flow if we already have a valid token for the selected org

fix: Update repo init command to not open browser window unless it needs to

---

oclif.manifest.json

- Added `gitlab.pr_insights` and `gitlab.code_usages` as possible caller values in the base command

chore: added gitlab pr insights and code usages as possible caller values

---

docs/generate.md
oclif.manifest.json
src/api/members.ts
src/commands/generate/types.test.ts
src/commands/generate/types.ts

feat: add info comments to type generator

---

src/commands/diff/__snapshots__/diff.test.ts.snap
src/commands/diff/diff.test.ts
src/commands/diff/index.ts

Handle PR links for gitlab in the response from the `dvc diff` command
Currently this only links to the relevant file. I'm not sure we can reliably link to the changed line

feat: Add handling for gitlab pr links

---

src/commands/login/sso.ts

The command `dvc login sso` fetches a personal access token and then uses it to fetch the available organizations. This was failing on the first attempt because the access token is written to the auth file but not made available to the current command

fix: Set personalAccessToken to be used by sso command

---

package.json

oclif uses the AbortController when parsing flag values which was added in node v15

chore: Update min node version to 16.0.0

---

src/commands/features/update.test.ts
src/commands/features/update.ts
src/ui/prompts/commonPrompts.ts
src/ui/prompts/listPrompts/listOptionsPrompt.ts
src/ui/prompts/listPrompts/variablesListPrompt.ts
src/ui/prompts/types.ts

Currently variations are always submitted with the feature update request. This causes a 412 error if the variations include a variable that was removed by the current command. Variations should not be included in the request unless they are modified.
Add an optional `checkForAdditionalProperties` method to the ListPrompt. The method returns a map of property names to values if an any additional properties were modified by the prompt (ex. variation values modified by the edit variable prompt)

fix: Don't include variations in feature update if they were not modified

---

.eslintrc
package.json
src/commands/cleanup/index.ts
src/commands/usages/__snapshots__/usages.test.ts.snap
src/commands/usages/index.ts
src/commands/usages/usages.test.ts
test-utils/fixtures/cleanup/javascript/[org_id]/test.js
test-utils/fixtures/usages/[org_id]/golang.go
test-utils/fixtures/usages/[org_id]/nodejs.js
test-utils/fixtures/usages/[org_id]/react.js
test-utils/fixtures/usages/[org_id]/sample.dart

- upgrade `minimatch` library
- use `minimatch.escape` to escape special characters for `include` and `exclude` flags so it can match on special characters when using `usages` and `cleanup`

chore: escape glob patterns for include exclude flags

---

src/auth/ApiAuth.test.ts
src/auth/ApiAuth.ts
src/auth/TokenCache.test.ts
src/auth/TokenCache.ts
src/utils/fileSystem.ts

When a token is ready to be refreshed, if multiple CLI requests are received simultaneously all refresh requests other than the first will fail. Since we refresh the token 1 hour before it expires, if a refresh request is already in progress we should just return the current token.
Also added test coverage to the ApiAuth class

fix: Only allow one refresh token request at a time

---

src/commands/targeting/enable.ts
src/commands/targeting/update.ts
src/utils/features/quickCreateFeatureUtils.ts
src/utils/targeting/index.ts

This prompt only shows up if you don't have any targeting rules, try to use `targeting update`, and then _only_ select `status` and set it to enabled. If you edit the targeting rules as part of the update it won't prompt to create one. Similarly, if you use the shortcut `targeting enable` it will trigger the prompt if you don't have any targeting rules. 
Selecting All Users just prompts to select variation and then creates the rule:
https://github.com/DevCycleHQ/cli/assets/25067948/ffdf8837-9431-49a7-9d66-6033dc0cfcf5
Selecting Custom Target prompts for name, variation, and filters:
Selecting Cancel ends the command:

Add prompt to create targets when enable an environment

---

.github/actions/update-vscode-extension/action.yml
.github/workflows/cli-release.yml

the extension calls `cliUtils.loadCli()` when it activates, which downloads the CLI based on the version defined in `constants.ts`, so i think it should be sufficient just to update the version defined there 
I set this to only run if the version bump is minor or patch
tested: https://github.com/DevCycleHQ/vscode-extension/pull/291

Add action to update vscode extension with latest version

---

oclif.manifest.json
src/auth/SSOAuth.ts

- when port is in use, add retry with another supported port to connect to

fix: added retry for connecting to a port not in use

---

README.md
oclif.manifest.json
src/api/apiClient.ts
src/commands/diff/__snapshots__/diff.test.ts.snap
src/commands/diff/diff.test.ts

- only logs API errors to `stdout` when the caller is the CLI
- adds test to to `diff` function to verify the `stdout` output

fix: limit API error logs to only render for CLI use-cases, not for other callers

---

README.md
oclif.manifest.json
src/auth/SSOAuth.ts
src/commands/authCommand.ts
src/commands/base.ts
src/commands/login/sso.ts

- feat: add --no-browser-auth option for authenticating via the CLI, primarily for use in environments that do not have access to a browser (i.e. running in some containers)

feat: add --no-browser-auth option for authenticating via the CLI

---

README.md
docs/usages.md
oclif.manifest.json
src/commands/base.ts
src/commands/usages/index.ts

- Read files in chunks rather than all at once
- Use a writable stream to output for optimization
- add option to output usages to a file

fix: ENOBUF bug fix attempt

---

src/utils/git/ls-files.ts

update the size so the larger repos dont fail while running usages
tested on a repo with ~50000 files

fix: update buffer size to 10MB

---

README.md
docs/generate.md
oclif.manifest.json
package.json
src/api/features.ts
src/api/zodClient.ts
src/commands/generate/__snapshots__/types.test.ts.snap
src/commands/generate/types.test.ts
src/commands/generate/types.ts

- check if each variable is part of a completed or archived feature and is not marked permanent
- if all of that is true, add a deprecation notice to the variable and its constant alias
- remove option for inline comments because it's not really that useful and requires maintaining two different code paths for comment generation, plus deprecation warnings dont work in that format

add deprecation notices to type generator output when feature is complete

---

README.md
oclif.manifest.json
src/api/apiClient.ts
src/api/features.ts
src/api/schemas.ts
src/api/variations.ts
src/api/zodClient.ts
src/auth/ApiAuth.ts
src/commands/diff/diff.test.ts
src/commands/features/__snapshots__/update.test.ts.snap
src/commands/features/create.test.ts
src/commands/features/create.ts
src/commands/features/get.test.ts
src/commands/features/list.test.ts
src/commands/features/update.test.ts
src/commands/variables/create.test.ts
src/commands/variables/create.ts
src/commands/variations/__snapshots__/create.test.ts.snap
src/commands/variations/__snapshots__/update.test.ts.snap
src/commands/variations/create.test.ts
src/commands/variations/update.test.ts
src/utils/features/quickCreateFeatureUtils.ts
test-utils/dvcTest.ts

- Update the CLI to use the v2 Features endpoint for most uses,
- kept variations until those are implemented in v2

chore: updated to use v2 feature endpoints

---

src/commands/generate/__snapshots__/types.test.ts.snap
src/commands/generate/types.ts

- update CLI to generate declare module interface merge that takes advantage of new type definitions
- add an option to disable the interface output
- deprecate the `--react` and `--next` flags

update CLI for declaration merging

---

README.md
oclif.manifest.json
src/commands/generate/types.ts

- apparently oclif will print deprecation warnings for a flag that isn't specified if it has a default value defined
- feels like a bug in oclif, but just removing the default value for now to fix it.

fix deprecation notice for type generator flags

---

src/api/zodClient.ts
src/commands/targeting/__snapshots__/update.test.ts.snap
src/commands/targeting/update.test.ts
src/ui/targetingTree.ts

- chore: add failing test for failing custom data targeting filter
- feat: add support for boolean, number and string values on a Target Definition with  `"subType": "customData"`

fix: add support for customData targeting filters with boolean, number or string values

---

.github/workflows/cli-release.yml

Pins the `peter-evans/repository-dispatch` action from `v2` tag to commit `bf47d102fdb849e755b0b0023ea3e81a44b6f570` to address CodeQL security alert.
- Updated `.github/workflows/cli-release.yml` to use pinned commit hash instead of mutable tag

Chore: pin action to specific commit

---

README.md
bin/mcp
bin/mcp.cmd
oclif.manifest.json
package.json
src/api/zodClient.ts
src/mcp/index.ts
src/mcp/server.ts
src/mcp/utils/auth.ts
yarn.lock

This PR enhances the DevCycle MCP server installation and usability with several key improvements:
- Added platform-specific bin wrappers (`bin/mcp`, `bin/mcp.cmd`) for better Windows/Unix compatibility
- Updated package.json to use bin wrappers instead of direct dist file reference
- Comprehensive installation guide with global and project-specific options
- Step-by-step configuration instructions for Cursor and Claude Desktop
- Added verification commands and troubleshooting section
- Added `--version`/`-v` and `--help`/`-h` flags to MCP server
- Dynamic version reporting from package.json (fixes hardcoded 0.0.1)
- Categorized startup errors with specific resolution guidance
- Enhanced authentication and project configuration error messages
- Rich tool error responses with actionable …

feat: improve MCP server installation

---

src/api/apiClient.ts
src/mcp/index.ts
src/mcp/utils/api.ts
src/mcp/utils/headers.ts

- Added MCP-specific headers to all API requests made through the MCP server
- Dynamically set the `command` field to the specific MCP tool name (e.g., "list_features", "create_project")
- Fixed bug in `setDVCReferrer` where `caller` parameter was ignored
- **New**: `src/mcp/utils/headers.ts` - Utilities for setting MCP headers
- **Updated**: `src/mcp/index.ts` - Initialize headers on server startup
- **Updated**: `src/mcp/utils/api.ts` - Set tool-specific command before each API call
- **Fixed**: `src/api/apiClient.ts` - Use `caller` parameter instead of hardcoded 'cli'
API requests now include proper identification:
- **CLI requests**: `{"command":"<cli_command>","caller":"cli","version":"<version>"}`
- **MCP requests**: `{"command":"<mcp_tool>","caller":"mcp","version":"<version>"}` …

feat(FDN-547): Add API request headers for MCP server tracking

---

src/api/results.ts
src/mcp/server.ts
src/mcp/tools/commonSchemas.ts
src/mcp/tools/featureTools.ts
src/mcp/tools/resultsTools.ts
src/mcp/types.ts

This PR adds support for DevCycle's evaluation results endpoints to the Model Context Protocol (MCP) server, enabling AI agents to query feature flag evaluation analytics.
- **Feature Total Evaluations**: Get evaluation analytics for a specific feature flag
- **Project Total Evaluations**: Get evaluation analytics across all features in a project
- `GET /v1/projects/{project}/features/{feature}/results/total-evaluations`
- `GET /v1/projects/{project}/results/total-evaluations`

feat: add result endpoints to MCP tools

---

src/mcp/tools/customPropertiesTools.ts
src/mcp/tools/environmentTools.ts
src/mcp/tools/featureTools.ts
src/mcp/tools/projectTools.ts
src/mcp/tools/resultsTools.ts
src/mcp/tools/selfTargetingTools.ts
src/mcp/tools/variableTools.ts

This PR enhances all MCP tool definitions with proper annotations to improve AI assistant behavior and user experience.
- **🚨 Destructive Hints**: Added `destructiveHint: true` to operations that can affect production environments (delete, update, enable/disable targeting)
- **📖 Human-Readable Titles**: Added `title` annotations to all tools for better UI display (e.g., "List Feature Flags", "Create Variable")  
- **👀 Read-Only Hints**: Added `readOnlyHint: true` to all non-destructive operations (list, get, fetch)
- AI assistants will now properly warn users before executing destructive operations
- Tool names are more user-friendly in UI contexts
- Clear categorization between read-only and modifying operations
- Better safety guardrails for production environment changes

feat: add destructive hints, titles, and readonly hints to mcp tools

---

src/mcp/utils/api.test.ts

Implements essential test coverage for the DevCycle MCP server's API client infrastructure.
- **6 focused tests** for `DevCycleApiClient` class in `src/mcp/utils/api.test.ts`
- Covers critical user-facing functionality without over-testing edge cases
- ✅ **Zodios error handling** - Ensures API schema mismatch recovery
- ✅ **Authentication workflows** - Validates auth requirements and error handling  
- ✅ **Dashboard link generation** - Tests core user workflow feature
- ✅ **Header management** - Verifies MCP tool tracking for telemetry

test: Add Minimal MCP API Client Tests

---

mcp-worker/src/consentScreen.ts

- updates to the mcp auth page to align it to the auth0 pages

Update the mcp auth page

---

src/mcp/tools/featureTools.ts

- updating some of the tool descriptions to make the interaction easier

Update tool descriptions

---

oclif.manifest.json
src/commands/environments/get.test.ts
src/commands/environments/get.ts
src/commands/features/get.test.ts
src/commands/features/get.ts
src/commands/variables/get.test.ts
src/commands/variables/get.ts
src/utils/parseKeysFromArgs.test.ts
src/utils/parseKeysFromArgs.ts

Implements [FDN-561](https://linear.app/devcycle/issue/FDN-561) to allow positional arguments as shorthand for the `--keys` flag in get commands.
Added support for positional arguments in:
- `dvc variables get`
- `dvc features get` 
- `dvc environments get`
```bash
dvc variables get --keys=var-one,var-two
dvc variables get var-one var-two        # space-separated
dvc variables get var-one,var-two        # comma-separated
dvc features get feature-one feature-two # works for all commands
```
✅ **Backward compatible** - existing `--keys` flag usage unchanged  
✅ **Precedence handling** - positional args take priority over `--keys`  
✅ **Flexible input** - supports both space and comma separation  
✅ **Updated help** - new examples in command documentation  
✅ **DRY implementation** - shared …

feat: add positional arguments support to get commands

---

mcp-worker/README.md
mcp-worker/src/projectSelectionTools.ts
package.json
scripts/measureMcpTokens.ts
src/api/zodClient.ts
src/mcp/tools/customPropertiesTools.ts
src/mcp/tools/featureTools.ts
src/mcp/tools/installTools.ts
src/mcp/tools/localProjectTools.ts
src/mcp/tools/projectTools.ts
src/mcp/tools/resultsTools.ts
src/mcp/tools/selfTargetingTools.ts
src/mcp/tools/variableTools.ts
src/mcp/types.ts
yarn.lock

- cleanup MCP tool types to reduce the AI context size used by our MCP server.

feat: cleanup mcp tool types

---

docs/mcp.md

docs: update MCP docs to match available tools

---

.github/workflows/cli-release.yml
.gitignore
mcp-worker/README.md
package.json
server.json
yarn.lock

- Add `server.json` for remote-only server:
- `name`: `com.devcycle/mcp`
- `remotes`: `https://mcp.devcycle.com/mcp` and `https://mcp.devcycle.com/sse`
- `repository` and `website_url` metadata
- Add schema validation:
- `yarn validate:server` using Ajv
- cache schema in `.schema/` and ignore via `.gitignore`
- Update CI (`.github/workflows/cli-release.yml`):
- install `mcp-publisher`
- sync only `.version` in `server.json` to tag
- DNS login using `MCP_KEY` from AWS Secrets (`DEVCYCLE_GITHUB_MCP_REGISTRY_PKEY`)
- publish to MCP Registry
- Remove package-based install from `server.json` (remote only for now)
- Secret required: `DEVCYCLE_GITHUB_MCP_REGISTRY_PKEY` (64‑hex Ed25519 private key seed)
- Validation: `yarn validate:server` passes
- Registry entry: curl …

feat: publish MCP server to registry

---

.github/workflows/cli-release.yml

fix: change MCP Registry key to DEVCYCLE_GITHUB_cli_MCP_REGISTRY_PKEY

---

mcp-worker/src/index.ts
package.json
src/api/apiClient.ts
src/commands/features/__snapshots__/update.test.ts.snap
src/mcp/utils/api.test.ts
yarn.lock

The `v2ApiClient` was not using the shared `axiosClient` instance, causing all `/v2/features` API calls from the MCP server to miss the MCP identification headers (`dvc-referrer` and `dvc-referrer-metadata`).
- Updated `v2ApiClient` creation in `src/api/apiClient.ts` to use the shared `axiosClient` instance with `validate: 'request'` option
- This ensures all v2 API calls properly identify themselves as originating from the MCP server

fix: ensure v2ApiClient uses shared axios instance for MCP headers
